"""expand char length in auth

Revision ID: 0fb54673727d
Revises: e73f119a2bda
Create Date: 2023-02-11 12:16:15.538560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0fb54673727d"
down_revision = "e73f119a2bda"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column("device", sa.Column("current_feed_id", sa.Integer(), nullable=True))
    # op.add_column("device", sa.Column("mac", sa.String(length=30), nullable=False))
    # with op.batch_alter_table("device") as batch_op:
    #     batch_op.create_foreign_key(None, "device", "feed", ["current_feed_id"], ["id"])
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "device", type_="foreignkey")
    op.drop_column("device", "mac")
    op.drop_column("device", "current_feed_id")
    # ### end Alembic commands ###
