"""tokens should be nullable

Revision ID: 1f80d0e09b1a
Revises: 410ae80a8741
Create Date: 2023-02-11 12:50:21.681433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1f80d0e09b1a"
down_revision = "410ae80a8741"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("device") as batch_op:
        batch_op.create_foreign_key("device", "feed", ["current_feed_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "device", type_="foreignkey")
    # ### end Alembic commands ###
