"""match server names

Revision ID: 3e7c4dd07eed
Revises: 1f80d0e09b1a
Create Date: 2023-02-11 15:55:42.802955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3e7c4dd07eed"
down_revision = "1f80d0e09b1a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("device") as batch_op:
        batch_op.add_column(sa.Column("feed_id", sa.Integer(), nullable=True))
        batch_op.drop_constraint("device", type_="foreignkey")
        batch_op.create_foreign_key("device", "feed", ["feed_id"], ["id"])
        batch_op.drop_column("current_feed_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("device", sa.Column("current_feed_id", sa.INTEGER(), nullable=True))
    op.drop_constraint(None, "device", type_="foreignkey")
    op.create_foreign_key("device", "device", "feed", ["current_feed_id"], ["id"])
    op.drop_column("device", "feed_id")
    # ### end Alembic commands ###
