"""tokens should be nullable

Revision ID: 410ae80a8741
Revises: 0fb54673727d
Create Date: 2023-02-11 12:46:55.652584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "410ae80a8741"
down_revision = "0fb54673727d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("auth") as batch_op:
        batch_op.alter_column("access_token", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "refresh_token", existing_type=sa.VARCHAR(), nullable=True
        )
    with op.batch_alter_table("auth") as batch_op:
        batch_op.create_foreign_key("device", "feed", ["current_feed_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "device", type_="foreignkey")
    op.alter_column("auth", "refresh_token", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("auth", "access_token", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
