"""add column for tenant_id

Revision ID: 58c9eeb42ff5
Revises: 3e7c4dd07eed
Create Date: 2023-02-12 18:36:22.431131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c9eeb42ff5'
down_revision = '3e7c4dd07eed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('tenant_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth', 'tenant_id')
    # ### end Alembic commands ###
