"""Update auth model with batch

Revision ID: 7aff26925e9e
Revises: e73f119a2bda
Create Date: 2023-02-08 08:35:05.407711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7aff26925e9e"
down_revision = "e73f119a2bda"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=90), nullable=False),
        sa.Column("password", sa.String(length=90), nullable=False),
        sa.Column("base_url", sa.String(length=180), nullable=False),
        sa.Column("access_token", sa.String(length=180), nullable=False),
        sa.Column("refresh_token", sa.String(length=180), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("device") as batch_op:
        batch_op.create_foreign_key(None, "device", "feed", ["current_feed_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "device", type_="foreignkey")
    op.drop_table("auth")
    # ### end Alembic commands ###
