"""Init

Revision ID: e73f119a2bda
Revises: 
Create Date: 2023-02-03 17:16:23.805095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e73f119a2bda"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feed",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=90), nullable=False),
        sa.Column("description", sa.String(length=180), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=90), nullable=False),
        sa.Column("path", sa.String(length=180), nullable=False),
        sa.Column("version", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feed_games",
        sa.Column("feed_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["feed.id"],
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["game.id"],
        ),
        sa.PrimaryKeyConstraint("feed_id", "game_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feed_games")
    op.drop_table("game")
    op.drop_table("feed")
    op.drop_table("device")
    # ### end Alembic commands ###
